### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by sabas** [php-edifact/edifact-mapping#3]
- [x] Segments D00B missing content
- [x] Service codes from D09A
- [x] Directory D16B
- [ ] Generate again the directories from D06A backwards
- [ ] Rerun on all directories

**Comment by swiffer** [comment]
Hi,

detected a spec failure in mscons.xml for D04B. Should be a group for SG10 but is a segment currently. Don't know if it's related to your TODO but as you're mentioning to Generate again directories for D06A backwards perhaps this is related.

```xml
`      <group id="SG9" maxrepeat="9999">
        <segment id="LIN" maxrepeat="1" required="true"/>
        <segment id="PIA" maxrepeat="9"/>
        <segment id="IMD" maxrepeat="9"/>
        <segment id="PRI" maxrepeat="9"/>
        <segment id="NAD" maxrepeat="9"/>
        <segment id="MOA" maxrepeat="9"/>
        <group id="SG10" maxrepeat="9999" required="true">
          <segment id="QTY" maxrepeat="1" required="true"/>
          <segment id="DTM" maxrepeat="9"/>
          <segment id="STS" maxrepeat="9"/>
        </group>
      </group>
```

Would love to see this fixed. Thanks!

**Comment by sabas** [comment]
Looks like the EDMDParser doesn't take in account groups that nested... :| Needs a smarter way to do that

**Comment by sabas** [comment]
Ok, I rewrote the parser and it works.

**Comment by sabas** [comment]
@swiffer I uploaded the newer data for D97A to D17A, could you please check?

**Comment by swiffer** [comment]
hey @sabas at least the the mscons i mentioned above is looking correct now. would be great to release an updated package on packgist.org
thanks!

**Comment by sabas** [comment]
Done
